-- Create the database if it doesn't exist
CREATE DATABASE IF NOT EXISTS SHAFAT_BMI_PHP_APP;

-- Select the database to use
USE SHAFAT_BMI_PHP_APP;

-- Create the AppUsers table
CREATE TABLE IF NOT EXISTS AppUsers (
    AppUserID INT AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(50) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,  
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create the BMIUsers table
CREATE TABLE IF NOT EXISTS BMIUsers (
    BMIUserID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Age INT,
    Sex ENUM('Male', 'Female', 'Other'),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create the BMIRecords table
CREATE TABLE IF NOT EXISTS BMIRecords (
    RecordID INT AUTO_INCREMENT PRIMARY KEY,
    BMIUserID INT,
    Height FLOAT NOT NULL,
    Weight FLOAT NOT NULL,
    BMI FLOAT NOT NULL,
    RecordedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (BMIUserID) REFERENCES BMIUsers(BMIUserID) ON DELETE CASCADE
);
